table si_qa_report
	lineageTag: c6a91c5f-a8bb-4ce6-88bd-39236abb0e91

	column department_en
		dataType: string
		lineageTag: 9404ee73-20a2-428c-a5e2-cf56260f8750
		summarizeBy: none
		sourceColumn: department_en

		annotation SummarizationSetBy = Automatic

	column department_fr
		dataType: string
		lineageTag: 41b0eb52-b54c-4f90-aef5-46b64ebcd0e4
		summarizeBy: none
		sourceColumn: department_fr

		annotation SummarizationSetBy = Automatic

	column org_id
		dataType: string
		lineageTag: e574105a-10a7-4759-bac0-f21c126116c2
		summarizeBy: none
		sourceColumn: org_id

		annotation SummarizationSetBy = Automatic

	column fiscal_yr
		dataType: string
		lineageTag: 823d6142-52f1-4c78-b00e-1371c62e0f6f
		summarizeBy: none
		sourceColumn: fiscal_yr

		annotation SummarizationSetBy = Automatic

	column service_id
		dataType: string
		lineageTag: 3d3cd9ee-3e42-4454-afe0-8159a996b57a
		summarizeBy: none
		sourceColumn: service_id

		annotation SummarizationSetBy = Automatic

	column service_name_en
		dataType: string
		lineageTag: 58dd7892-279c-413a-a2d4-1638381a121e
		summarizeBy: none
		sourceColumn: service_name_en

		annotation SummarizationSetBy = Automatic

	column service_name_fr
		dataType: string
		lineageTag: e260565c-7e4f-4245-9d75-05b2e6331246
		summarizeBy: none
		sourceColumn: service_name_fr

		annotation SummarizationSetBy = Automatic

	column issue
		dataType: string
		lineageTag: 526b12d4-b7af-4c67-b019-1e7e9b8ab35b
		summarizeBy: none
		sourceColumn: issue

		annotation SummarizationSetBy = Automatic

	column severity_en
		dataType: string
		lineageTag: 88f179e8-a148-463e-835e-f1a31e1030d7
		summarizeBy: none
		sourceColumn: severity_en

		annotation SummarizationSetBy = Automatic

	column description_en
		dataType: string
		lineageTag: ef25cfcf-05d3-487f-8c83-db27cacfa70f
		summarizeBy: none
		sourceColumn: description_en

		annotation SummarizationSetBy = Automatic

	column action_en
		dataType: string
		lineageTag: c8a2263b-5fa9-4f13-84a4-475053217727
		summarizeBy: none
		sourceColumn: action_en

		annotation SummarizationSetBy = Automatic

	column severity_fr
		dataType: string
		lineageTag: 05107b51-cb3b-463a-974b-22884a01628c
		summarizeBy: none
		sourceColumn: severity_fr

		annotation SummarizationSetBy = Automatic

	column description_fr
		dataType: string
		lineageTag: 023a597b-6f94-4ca7-82ab-b5f5d33f1a12
		summarizeBy: none
		sourceColumn: description_fr

		annotation SummarizationSetBy = Automatic

	column action_fr
		dataType: string
		lineageTag: 38886c8b-c0fd-4fd8-b606-cc3b84d0e6a3
		summarizeBy: none
		sourceColumn: action_fr

		annotation SummarizationSetBy = Automatic

	column context
		dataType: string
		lineageTag: e0598684-c8c1-4580-a7a5-fb97e1127ed2
		summarizeBy: none
		sourceColumn: context

		annotation SummarizationSetBy = Automatic

	column fy_org_id_service_id = [fiscal_yr]&"_"&[org_id]&"_"&[service_id]
		lineageTag: 8cd33514-c55a-4ee2-b4b3-a04e90b98902
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition si_qa_report = m
		mode: import
		queryGroup: qa
		source =
				let
				    Source = Csv.Document(Web.Contents("https://github.com/gcperformance/service-data/releases/latest/download/si_qa_report.csv"),[Delimiter=";", Columns=null, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Removed Bottom Rows" = Table.RemoveLastN(Source,2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Bottom Rows", [PromoteAllScalars=true])
				in
				    #"Promoted Headers"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

